/**
 * CodeMate 智学工坊 — 当前版本聚焦配置
 * 全站集中展示《数据结构与算法》一门课程
 */

import type { Course } from '../types'

export const COURSE_FOCUS = {
  /** 主课程名称 */
  courseName: '数据结构与算法',
  /** 产品副标题 */
  productSubtitle: '数据结构与算法个性化学习资源平台',
  /** 平台简介 */
  platformIntro: '围绕复杂度、线性结构、递归、树、图、排序、查找等核心模块，生成个性化学习资源',

  /** 先修基础（仅在画像页作为"先修基础"询问） */
  prerequisiteTopics: [
    '程序设计基础',
    '离散数学',
    '编程语言基础',
    '数学基础',
  ] as const,

  /** 示例知识点（用于资源生成、辅导评估默认主题） */
  exampleTopics: [
    '递归调用栈',
    '二叉树遍历',
    '图的 BFS 与 DFS',
    '快速排序',
    '动态规划入门',
  ] as const,

  /** 数据结构内部模块 */
  modules: [
    {
      id: 'complexity',
      name: '复杂度分析',
      stage: '基础模块',
      keywords: ['时间复杂度', '空间复杂度', '大O表示法', '最好/最坏/平均', '渐进分析'],
      difficulties: ['大O表示法的直观理解', '嵌套循环复杂度计算', '递归算法复杂度分析'],
      summary: '理解算法效率的度量方式，掌握时间复杂度与空间复杂度的分析方法。',
    },
    {
      id: 'linear-list',
      name: '线性表',
      stage: '基础模块',
      keywords: ['顺序表', '链表', '单链表', '双向链表', '循环链表', '插入', '删除'],
      difficulties: ['链表指针操作', '头结点与尾结点处理', '双向链表插入删除'],
      summary: '掌握顺序表与链式存储结构的原理、实现及适用场景。',
    },
    {
      id: 'stack-queue',
      name: '栈与队列',
      stage: '核心模块',
      keywords: ['栈', '队列', 'LIFO', 'FIFO', '循环队列', '双端队列', '表达式求值'],
      difficulties: ['栈在递归中的作用', '循环队列判空判满', '表达式转换与求值'],
      summary: '理解栈与队列的逻辑结构、存储实现及在算法中的经典应用。',
    },
    {
      id: 'recursion-callstack',
      name: '递归与调用栈',
      stage: '建议优先学习',
      keywords: ['递归', '调用栈', '基准情形', '递归出口', '栈帧', '尾递归', '递推'],
      difficulties: ['递归到非递归的转换', '调用栈帧的理解', '递归出口的正确设置'],
      summary: '深入理解递归思想、调用栈机制，掌握递归算法的设计与调试。',
    },
    {
      id: 'tree',
      name: '树与二叉树',
      stage: '核心模块',
      keywords: ['二叉树', '前序遍历', '中序遍历', '后序遍历', '层序遍历', 'BST', 'AVL', '堆'],
      difficulties: ['遍历算法的递归与非递归实现', '二叉搜索树的插入删除', '平衡树的旋转操作'],
      summary: '系统学习树结构，掌握二叉树遍历、二叉搜索树及平衡树的核心算法。',
    },
    {
      id: 'graph',
      name: '图结构与图算法',
      stage: '进阶模块',
      keywords: ['图', '邻接矩阵', '邻接表', 'DFS', 'BFS', '最短路径', 'Dijkstra', '拓扑排序'],
      difficulties: ['DFS与BFS的选择与应用', '最短路径算法理解', '图的存储结构选择'],
      summary: '学习图的存储结构与遍历算法，掌握最短路径、拓扑排序等经典图算法。',
    },
    {
      id: 'sort-search',
      name: '排序与查找',
      stage: '核心模块',
      keywords: ['快速排序', '归并排序', '堆排序', '二分查找', '线性查找', '稳定性', '复杂度'],
      difficulties: ['快速排序的partition过程', '归并排序的合并逻辑', '各排序算法稳定性对比'],
      summary: '掌握经典排序与查找算法的原理、实现及性能对比。',
    },
    {
      id: 'hash',
      name: '散列表',
      stage: '进阶模块',
      keywords: ['散列表', '哈希函数', '冲突解决', '链地址法', '开放定址', '负载因子'],
      difficulties: ['哈希函数的设计', '冲突解决策略选择', '负载因子与rehash'],
      summary: '理解散列表的原理与实现，掌握哈希函数设计与冲突解决方法。',
    },
    {
      id: 'dp',
      name: '动态规划入门',
      stage: '进阶模块',
      keywords: ['动态规划', '最优子结构', '重叠子问题', '状态定义', '状态转移', '记忆化搜索'],
      difficulties: ['状态定义与转移方程', '最优子结构的识别', '自顶向下与自底向上'],
      summary: '入门动态规划思想，掌握状态定义、转移方程和经典DP问题的求解。',
    },
    {
      id: 'ds-project',
      name: '综合项目实践',
      stage: '综合应用',
      keywords: ['项目', '综合', '应用', '实践', '系统设计', '数据结构选择'],
      difficulties: ['数据结构的选择与组合', '实际问题的抽象建模', '性能优化与测试'],
      summary: '将所学数据结构与算法知识应用于综合项目，培养实际建模与编码能力。',
    },
  ],

  /** 模块标签 */
  stageLabels: {
    '建议优先学习': { color: 'bg-amber-50 text-amber-700 border-amber-100', text: '建议优先学习' },
    '基础模块': { color: 'bg-blue-50 text-blue-700 border-blue-100', text: '基础模块' },
    '核心模块': { color: 'bg-primary-50 text-primary-700 border-primary-100', text: '核心模块' },
    '进阶模块': { color: 'bg-purple-50 text-purple-700 border-purple-100', text: '进阶模块' },
    '综合应用': { color: 'bg-emerald-50 text-emerald-700 border-emerald-100', text: '综合应用' },
  } as Record<string, { color: string; text: string }>,

  /** 诊断题示例（用于辅导评估默认展示） */
  exampleDiagnosisQuestions: [
    '递归调用栈为什么容易弄混？',
    '前序遍历和中序遍历有什么区别？',
    'BFS 和 DFS 应该怎么选择？',
    '快速排序为什么平均复杂度是 O(nlogn)？',
    '动态规划为什么要定义状态？',
  ],
} as const

/** 数据结构与算法全部模块 — 供 CourseCenter、Dashboard、CourseMap 直接使用 */
export const dataStructureModules: Course[] = [
  {
    id: 'complexity',
    name: '复杂度分析',
    description: '理解算法效率的度量方式，掌握时间复杂度与空间复杂度的分析方法，为后续算法学习建立评估框架。',
    summary: '掌握大O表示法与渐进分析方法。',
    stage: '基础模块',
    prerequisites: [],
    related_courses: ['linear-list', 'recursion-callstack', 'sort-search'],
    knowledge_points: ['时间复杂度', '空间复杂度', '大O表示法', '最好/最坏/平均', '渐进分析', '递归复杂度'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['大O表示法的直观理解', '嵌套循环复杂度计算', '递归算法复杂度分析'],
    learning_suggestion: '建议先从简单循环的复杂度分析入手，逐步过渡到嵌套循环和递归。多用具体代码实例对比不同算法的复杂度差异。',
    color: '#7c3aed',
  },
  {
    id: 'linear-list',
    name: '线性表',
    description: '掌握顺序表与链式存储结构的原理、实现及适用场景，理解不同存储方式对增删改查操作效率的影响。',
    summary: '掌握顺序表与链表的原理和实现。',
    stage: '基础模块',
    prerequisites: [],
    related_courses: ['stack-queue', 'tree', 'hash'],
    knowledge_points: ['顺序表', '单链表', '双向链表', '循环链表', '头插法/尾插法', '结点删除'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['链表指针操作', '头结点与尾结点的边界处理', '双向链表插入删除'],
    learning_suggestion: '建议多画图理解指针的指向变化，先实现单链表的基本操作再扩展到双向链表和循环链表。',
    color: '#6d28d9',
  },
  {
    id: 'stack-queue',
    name: '栈与队列',
    description: '理解栈与队列的逻辑结构、存储实现方式，掌握它们在表达式求值、括号匹配、BFS等算法中的经典应用。',
    summary: '理解LIFO与FIFO结构及其应用场景。',
    stage: '核心模块',
    prerequisites: ['linear-list'],
    related_courses: ['recursion-callstack', 'tree', 'graph'],
    knowledge_points: ['栈', '队列', 'LIFO', 'FIFO', '循环队列', '双端队列', '表达式求值', '括号匹配'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['栈在递归中的作用', '循环队列判空判满条件', '中缀转后缀表达式'],
    learning_suggestion: '建议从栈和队列的基本操作入手，通过表达式求值和括号匹配等经典问题加深理解，再尝试BFS中的队列应用。',
    color: '#8b5cf6',
  },
  {
    id: 'recursion-callstack',
    name: '递归与调用栈',
    description: '深入理解递归思想与系统调用栈机制，掌握递归算法的设计范式、调试方法以及递归到非递归的转换技巧。',
    summary: '理解递归思想与调用栈的深层机制。',
    stage: '建议优先学习',
    prerequisites: ['stack-queue'],
    related_courses: ['tree', 'sort-search', 'dp'],
    knowledge_points: ['递归三要素', '调用栈', '栈帧', '基准情形', '尾递归', '递归转非递归', '分治思想'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['递归到非递归的转换', '调用栈帧的直观理解', '递归出口的正确设置', '递归深度与栈溢出'],
    learning_suggestion: '建议先画图理解递归调用过程中栈帧的变化，从斐波那契和阶乘等简单例子开始，再用树的遍历加深理解。',
    color: '#a78bfa',
  },
  {
    id: 'tree',
    name: '树与二叉树',
    description: '系统学习树结构，掌握二叉树遍历、二叉搜索树、平衡树及堆的核心算法，理解树结构在索引和优先队列中的应用。',
    summary: '树结构的核心：遍历、搜索与平衡。',
    stage: '核心模块',
    prerequisites: ['recursion-callstack', 'stack-queue'],
    related_courses: ['graph', 'sort-search', 'hash'],
    knowledge_points: ['二叉树', '前序/中序/后序遍历', '层序遍历', 'BST', 'AVL树', '堆', '哈夫曼树'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['遍历的递归与非递归实现', 'BST的删除操作', 'AVL的旋转操作', '堆的向上/向下调整'],
    learning_suggestion: '建议从二叉树的四种遍历方式入手，理解递归版后再尝试非递归栈实现，再逐步深入学习BST和平衡树。',
    color: '#c4b5fd',
  },
  {
    id: 'graph',
    name: '图结构与图算法',
    description: '学习图的存储结构与遍历算法，掌握最短路径、最小生成树、拓扑排序等经典图算法及其实际应用。',
    summary: '掌握图的表示、遍历与经典算法。',
    stage: '进阶模块',
    prerequisites: ['tree', 'stack-queue'],
    related_courses: ['dp', 'sort-search'],
    knowledge_points: ['邻接矩阵', '邻接表', 'DFS', 'BFS', 'Dijkstra', 'Floyd', '拓扑排序', '最小生成树'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['DFS与BFS的选择与应用场景', '最短路径算法的直观理解', '图的存储结构选择', '拓扑排序的合法性判断'],
    learning_suggestion: '建议先从图的两种存储方式入手，再逐个实现DFS和BFS，理解两者的差异和适用场景后再学习最短路径算法。',
    color: '#6366f1',
  },
  {
    id: 'sort-search',
    name: '排序与查找',
    description: '掌握经典排序与查找算法的原理、实现及性能对比，理解不同算法在不同数据特征下的适用场景。',
    summary: '经典排序与查找算法的原理与对比。',
    stage: '核心模块',
    prerequisites: ['recursion-callstack', 'linear-list'],
    related_courses: ['tree', 'dp', 'hash'],
    knowledge_points: ['冒泡/选择/插入排序', '快速排序', '归并排序', '堆排序', '二分查找', '稳定性', '复杂度对比'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['快速排序partition过程', '归并排序的合并与递归', '各排序算法稳定性对比', '二分查找的边界条件'],
    learning_suggestion: '建议从简单排序（冒泡、选择、插入）入手，理解稳定性概念后再学快速排序和归并排序，最后对比所有算法的优缺点。',
    color: '#7c3aed',
  },
  {
    id: 'hash',
    name: '散列表',
    description: '理解散列表的原理与实现，掌握哈希函数设计、冲突解决策略以及散列表在实际系统中的广泛应用。',
    summary: '散列表：高效查找的核心数据结构。',
    stage: '进阶模块',
    prerequisites: ['linear-list', 'sort-search'],
    related_courses: ['tree', 'ds-project'],
    knowledge_points: ['散列表', '哈希函数', '链地址法', '开放定址法', '负载因子', 'rehash', '一致性哈希'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['哈希函数的设计原则', '冲突解决策略的选择', '负载因子与rehash的时机', '开放定址的删除问题'],
    learning_suggestion: '建议先用简单的取模哈希和链地址法实现一个散列表，再对比不同冲突解决策略的性能差异。',
    color: '#6d28d9',
  },
  {
    id: 'dp',
    name: '动态规划入门',
    description: '入门动态规划思想，掌握状态定义、转移方程和经典DP问题，理解最优子结构与重叠子问题的核心概念。',
    summary: '掌握状态定义与转移方程的设计方法。',
    stage: '进阶模块',
    prerequisites: ['recursion-callstack', 'sort-search'],
    related_courses: ['graph', 'ds-project'],
    knowledge_points: ['最优子结构', '重叠子问题', '状态定义', '状态转移方程', '记忆化搜索', '背包问题', 'LCS'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['状态定义与转移方程的推导', '最优子结构的识别', '自顶向下与自底向上的选择', '空间优化技巧'],
    learning_suggestion: '建议从斐波那契数列的记忆化搜索入手，理解重叠子问题后再学习经典的背包问题和LCS，逐步建立DP思维。',
    color: '#8b5cf6',
  },
  {
    id: 'ds-project',
    name: '综合项目实践',
    description: '将所学数据结构与算法知识应用于综合项目，培养实际问题的抽象建模能力、数据结构选择能力和代码工程能力。',
    summary: '综合运用数据结构解决实际问题。',
    stage: '综合应用',
    prerequisites: ['tree', 'graph', 'sort-search', 'hash'],
    related_courses: ['dp'],
    knowledge_points: ['数据结构选型', '算法设计', '复杂度优化', '实际建模', '测试与调试', '项目文档'],
    resource_types: ['讲解文档', '思维导图', '代码示例', '分层练习', '拓展阅读', '项目案例'],
    typical_difficulties: ['实际问题的抽象建模', '多种数据结构的组合使用', '性能瓶颈的分析与优化'],
    learning_suggestion: '建议从小型项目（如表达式计算器、迷宫求解）开始，逐步挑战复杂项目（如简单搜索引擎、路径规划器）。',
    color: '#a78bfa',
  },
]
